#!/bin/bash

#apt install samba cifs-utils smbclient
device="/dev/mmcblk0"
mnt="/mnt/mosave1d"
dir="$mnt/zBackup"
fname="$dir/${HOSTNAME}_$(date +"%Y_%m_%d_%I_%M_%p").img.7z"

if [ ! -d "$mnt" ]; then 
  mkdir "$mnt"
fi


if [ ! -d "$dir" ]; then 
  umount "$mnt"
  mount -t cifs -o username=admin //1.1.1.2/d "$mnt"
fi


if [ ! -d "$dir" ]; then 
  echo -e -n "\033[1;31m Error mounting //mosave/d to $mnt\033[0m\n"
  exit
fi

echo "OK"
dd if="$device" bs=50M| 7zr a -bd -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on -si "$fname"

umount $mnt
