#!/bin/bash

#apt install samba cifs-utils smbclient
device="/dev/mmcblk2"
mnt="/mnt/mosave1d"
dir="$mnt/zBackup"
fname="$dir/{$HOSTNAME}.img"


if [ ! -d "$dir" ]; then 
  umount "$mnt"
  mount -t cifs -o username=admin //1.1.1.2/d "$mnt"
fi


if [ ! -d "$dir" ]; then 
  echo -e -n "\033[1;31m Error mounting //mosave/d to $mnt\033[0m\n"
  exit
fi

echo "OK"
#parted $device rm 2
#parted $device rm 1
#parted $device mkpart primary ext4 1MiB 100%

dd if="$fname" of="$device" bs=50M

umount $mnt
