#!/bin/sh

### BEGIN INIT INFO
# Provides:          lvt_client
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Lite Voice Terminal client service
# Description:       Lite Voice Terminal client service
### END INIT INFO

DIR=/home/pi/LVTerminal
DAEMON=$DIR/lvt_client.sh
DAEMON_NAME=lvt_client

DAEMON_OPTS="-q" 
DAEMON_USER=pi
PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

do_start () {
    log_daemon_msg "Starting Lite Voice Terminal client service"
    start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas $DAEMON -- $DAEMON_OPTS
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping Lite Voice Terminal client service"
    #start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    pkill -f "lvt_client.py"
    log_end_msg $?
}

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;

    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0